# http://docs.ansible.com/ansible/intro_windows.html#windows-how-does-it-work
ansible_connection: winrm

# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore